### ISSUE TITLE
mqtt-listener_write_proxon_influxdb.py - Loop in on_connect

### ISSUE THREAD

**Issue by m4dmin** [m4dmin/proxon-control#2]
2021-10-19 16:20:43,333 - DEBUG - Debug Log
2021-10-19 16:20:43,345 - INFO - Creating new influxDB client
2021-10-19 16:20:43,346 - INFO - Creating new MQTT instance
2021-10-19 16:20:43,346 - INFO - Connection to MQTT broker
2021-10-19 16:20:43,347 - INFO - Starting loop MQTT forever
2021-10-19 16:20:43,347 - DEBUG - TEST CONNECT
2021-10-19 16:20:43,348 - INFO - Connected with result code 0
2021-10-19 16:20:43,348 - DEBUG - state_topic - /proxon/mode/wp_modus_betriebsart/state
2021-10-19 16:20:43,348 - DEBUG - Register Array - [16, 0, 0, 3, True, 'wp_modus_betriebsart', 'mode', 'Betriebsart']
2021-10-19 16:20:43,376 - DEBUG - Value: 3
2021-10-19 16:20:43,376 - INFO - Betriebsart                        : 3 mode
2021-10-19 16:20:43,376 - DEBUG - {'measurement': 'wp_modus_betriebsart', 'tags': {'instance': 'PROD', 'source': 'PROD'}, 'fields': {'mode': 3}}
2021-10-19 16:20:43,377 - DEBUG - state_topic - /proxon/switch/wp_on-off_kuehlung/state
2021-10-19 16:20:43,377 - DEBUG - Register Array - [62, 0, 0, 3, '', 'wp_on-off_kuehlung', 'switch', 'Kühlung an/aus']
2021-10-19 16:20:43,408 - DEBUG - Value: 0
2021-10-19 16:20:43,408 - INFO - Kühlung an/aus                     : 0 switch
2021-10-19 16:20:43,408 - DEBUG - {'measurement': 'wp_on-off_kuehlung', 'tags': {'instance': 'PROD', 'source': 'PROD'}, 'fields': {'switch': 0}}
2021-10-19 16:20:43,408 - DEBUG - state_topic - /proxon/switch/t300_on-off_heizstab/state
2021-10-19 16:20:43,409 - DEBUG - Register Array - [2001, 0, 0, 3, True, 't300_on-off_heizstab', 'switch', 'Heizstab an/aus']
2021-10-19 16:20:43,424 - DEBUG - Value: 0
2021-10-19 16:20:43,424 - INFO - Heizstab an/aus                    : 0 switch
2021-10-19 16:20:43,424 - DEBUG - {'measurement': 't300_on-off_heizstab', 'tags': {'instance': 'PROD', 'source': 'PROD'}, 'fields': {'switch': 0}}
2021-10-19 16:20:43,424 - DEBUG - state_topic - /proxon/temp/wp_soll-temp_zone1/state
2021-10-19 16:20:43,424 - DEBUG - Register Array - [70, 2, 1, 3, True, 'wp_soll-temp_zone1', 'temp', 'Wohnen  (Zone1) Soll-Temperatur']
2021-10-19 16:20:43,440 - DEBUG - Value: 22.5
2021-10-19 16:20:43,440 - DEBUG - Value: 23.0
2021-10-19 16:20:43,440 - INFO - Wohnen  (Zone1) Soll-Temperatur    : 23.0 temp
2021-10-19 16:20:43,440 - DEBUG - {'measurement': 'wp_soll-temp_zone1', 'tags': {'instance': 'PROD', 'source': 'PROD'}, 'fields': {'temp': 23.0}}
2021-10-19 16:20:43,440 - DEBUG - state_topic - /proxon/temp/wp_soll-temp_zone2/state
2021-10-19 16:20:43,440 - DEBUG - Register Array - [75, 2, 1, 3, True, 'wp_soll-temp_zone2', 'temp', 'Büro KG (Zone2) Soll-Temperatur']
2021-10-19 16:20:43,456 - DEBUG - Value: 19
2021-10-19 16:20:43,456 - INFO - Büro KG (Zone2) Soll-Temperatur    : 19 temp
2021-10-19 16:20:43,456 - DEBUG - {'measurement': 'wp_soll-temp_zone2', 'tags': {'instance': 'PROD', 'source': 'PROD'}, 'fields': {'temp': 19}}
2021-10-19 16:20:43,456 - DEBUG - state_topic - /proxon/temp/t300_soll-temp_wasser/state
2021-10-19 16:20:43,456 - DEBUG - Register Array - [2000, 1, 1, 3, True, 't300_soll-temp_wasser', 'temp', 'Wasser Soll-Temperatur']
2021-10-19 16:20:43,472 - DEBUG - Value: 48
2021-10-19 16:20:43,472 - INFO - Wasser Soll-Temperatur             : 48 temp
2021-10-19 16:20:43,472 - DEBUG - {'measurement': 't300_soll-temp_wasser', 'tags': {'instance': 'PROD', 'source': 'PROD'}, 'fields': {'temp': 48}}
2021-10-19 16:20:43,473 - DEBUG - state_topic - /proxon/temp/t300_schwelle-temp_wasser/state
2021-10-19 16:20:43,473 - DEBUG - Register Array - [2003, 1, 1, 3, True, 't300_schwelle-temp_wasser', 'temp', 'Wasser Temperatur-Schwelle Heizstab']
2021-10-19 16:20:43,488 - DEBUG - Value: 43
2021-10-19 16:20:43,488 - INFO - Wasser Temperatur-Schwelle Heizstab: 43 temp
2021-10-19 16:20:43,488 - DEBUG - {'measurement': 't300_schwelle-temp_wasser', 'tags': {'instance': 'PROD', 'source': 'PROD'}, 'fields': {'temp': 43}}
2021-10-19 16:20:43,488 - DEBUG - state_topic - /proxon/min/wp_restzeit_intensivlueftung/state
2021-10-19 16:20:43,488 - DEBUG - Register Array - [133, 0, 0, 3, True, 'wp_restzeit_intensivlueftung', 'min', 'Intensivlüftung Restzeit']
2021-10-19 16:20:43,504 - DEBUG - Value: 0
2021-10-19 16:20:43,504 - INFO - Intensivlüftung Restzeit           : 0 min
2021-10-19 16:20:43,504 - DEBUG - {'measurement': 'wp_restzeit_intensivlueftung', 'tags': {'instance': 'PROD', 'source': 'PROD'}, 'fields': {'min': 0}}
2021-10-19 16:20:43,511 - INFO - Closed running processes
2021-10-19 16:20:44,348 - INFO - Connected with result code 0
2021-10-19 16:20:45,351 - DEBUG - TEST CONNECT
2021-10-19 16:20:45,351 - INFO - Connected with result code 0
2021-10-19 16:20:45,351 - DEBUG - state_topic - /proxon/mode/wp_modus_betriebsart/state
2021-10-19 16:20:45,351 - DEBUG - Register Array - [16, 0, 0, 3, True, 'wp_modus_betriebsart', 'mode', 'Betriebsart']
2021-10-19 16:20:45,373 - DEBUG - Value: 3
2021-10-19 16:20:45,374 - INFO - Betriebsart                        : 3 mode
2021-10-19 16:20:45,374 - DEBUG - {'measurement': 'wp_modus_betriebsart', 'tags': {'instance': 'PROD', 'source': 'PROD'}, 'fields': {'mode': 3}}
2021-10-19 16:20:45,374 - DEBUG - state_topic - /proxon/switch/wp_on-off_kuehlung/state
2021-10-19 16:20:45,374 - DEBUG - Register Array - [62, 0, 0, 3, '', 'wp_on-off_kuehlung', 'switch', 'Kühlung an/aus']
2021-10-19 16:20:45,389 - DEBUG - Value: 0
2021-10-19 16:20:45,390 - INFO - Kühlung an/aus                     : 0 switch
2021-10-19 16:20:45,390 - DEBUG - {'measurement': 'wp_on-off_kuehlung', 'tags': {'instance': 'PROD', 'source': 'PROD'}, 'fields': {'switch': 0}}
2021-10-19 16:20:45,390 - DEBUG - state_topic - /proxon/switch/t300_on-off_heizstab/state
2021-10-19 16:20:45,390 - DEBUG - Register Array - [2001, 0, 0, 3, True, 't300_on-off_heizstab', 'switch', 'Heizstab an/aus']
2021-10-19 16:20:45,405 - DEBUG - Value: 0
2021-10-19 16:20:45,405 - INFO - Heizstab an/aus                    : 0 switch
2021-10-19 16:20:45,405 - DEBUG - {'measurement': 't300_on-off_heizstab', 'tags': {'instance': 'PROD', 'source': 'PROD'}, 'fields': {'switch': 0}}
2021-10-19 16:20:45,406 - DEBUG - state_topic - /proxon/temp/wp_soll-temp_zone1/state
2021-10-19 16:20:45,406 - DEBUG - Register Array - [70, 2, 1, 3, True, 'wp_soll-temp_zone1', 'temp', 'Wohnen  (Zone1) Soll-Temperatur']
2021-10-19 16:20:45,437 - DEBUG - Value: 22.5
2021-10-19 16:20:45,438 - DEBUG - Value: 23.0
2021-10-19 16:20:45,438 - INFO - Wohnen  (Zone1) Soll-Temperatur    : 23.0 temp
2021-10-19 16:20:45,438 - DEBUG - {'measurement': 'wp_soll-temp_zone1', 'tags': {'instance': 'PROD', 'source': 'PROD'}, 'fields': {'temp': 23.0}}
2021-10-19 16:20:45,438 - DEBUG - state_topic - /proxon/temp/wp_soll-temp_zone2/state
2021-10-19 16:20:45,438 - DEBUG - Register Array - [75, 2, 1, 3, True, 'wp_soll-temp_zone2', 'temp', 'Büro KG (Zone2) Soll-Temperatur']
2021-10-19 16:20:45,453 - DEBUG - Value: 19
2021-10-19 16:20:45,453 - INFO - Büro KG (Zone2) Soll-Temperatur    : 19 temp
2021-10-19 16:20:45,453 - DEBUG - {'measurement': 'wp_soll-temp_zone2', 'tags': {'instance': 'PROD', 'source': 'PROD'}, 'fields': {'temp': 19}}
2021-10-19 16:20:45,454 - DEBUG - state_topic - /proxon/temp/t300_soll-temp_wasser/state
2021-10-19 16:20:45,454 - DEBUG - Register Array - [2000, 1, 1, 3, True, 't300_soll-temp_wasser', 'temp', 'Wasser Soll-Temperatur']
2021-10-19 16:20:45,469 - DEBUG - Value: 48
2021-10-19 16:20:45,469 - INFO - Wasser Soll-Temperatur             : 48 temp
2021-10-19 16:20:45,469 - DEBUG - {'measurement': 't300_soll-temp_wasser', 'tags': {'instance': 'PROD', 'source': 'PROD'}, 'fields': {'temp': 48}}
2021-10-19 16:20:45,470 - DEBUG - state_topic - /proxon/temp/t300_schwelle-temp_wasser/state
2021-10-19 16:20:45,470 - DEBUG - Register Array - [2003, 1, 1, 3, True, 't300_schwelle-temp_wasser', 'temp', 'Wasser Temperatur-Schwelle Heizstab']
2021-10-19 16:20:45,486 - DEBUG - Value: 43
2021-10-19 16:20:45,486 - INFO - Wasser Temperatur-Schwelle Heizstab: 43 temp
2021-10-19 16:20:45,486 - DEBUG - {'measurement': 't300_schwelle-temp_wasser', 'tags': {'instance': 'PROD', 'source': 'PROD'}, 'fields': {'temp': 43}}
2021-10-19 16:20:45,486 - DEBUG - state_topic - /proxon/min/wp_restzeit_intensivlueftung/state
2021-10-19 16:20:45,486 - DEBUG - Register Array - [133, 0, 0, 3, True, 'wp_restzeit_intensivlueftung', 'min', 'Intensivlüftung Restzeit']
2021-10-19 16:20:45,501 - DEBUG - Value: 0
2021-10-19 16:20:45,501 - INFO - Intensivlüftung Restzeit           : 0 min
2021-10-19 16:20:45,502 - DEBUG - {'measurement': 'wp_restzeit_intensivlueftung', 'tags': {'instance': 'PROD', 'source': 'PROD'}, 'fields': {'min': 0}}
2021-10-19 16:20:45,506 - INFO - Closed running processes
2021-10-19 16:20:46,353 - INFO - Connected with result code 0

**Comment by m4dmin** [comment]
madmin@server-prod-ubuntu-1:~/proxon-control/python$ sudo ./read-data-write-to-db.py
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "./read-data-write-to-db.py", line 196, in <module>
    client.connect(mqtt_broker_address)
  File "/home/madmin/.local/lib/python3.6/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/home/madmin/.local/lib/python3.6/site-packages/paho/mqtt/client.py", line 1119, in reconnect
    return self._send_connect(self._keepalive)
  File "/home/madmin/.local/lib/python3.6/site-packages/paho/mqtt/client.py", line 2687, in _send_connect
    self._client_id
  File "/home/madmin/.local/lib/python3.6/site-packages/paho/mqtt/client.py", line 2398, in _easy_log
    self.on_log(self, self._userdata, level, buf)
  File "./read-data-write-to-db.py", line 115, in on_log
    logger.debug("MQTT-Log: ",buf)
Message: 'MQTT-Log: '
Arguments: ("Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b'proxon'",)

**Comment by m4dmin** [comment]
client = mqtt.Client(mqtt_client_name, True, None, mqtt.MQTTv31)

2021-11-08 19:39:37,421 - DEBUG - 400: {"error":"partial write: field type conflict: input field \"temp\" on measurement \"wp_soll-temp_zone2\" is type integer, already exists as type float dropped=3"}
